### ISSUE TITLE
Adding GitHub Actions

### ISSUE THREAD

**Issue by szabgab** [googleads/google-ads-perl#108]
I am using the [CPAN Digger](https://cpan-digger.perlmaven.com/) to monitor recently uploaded Perl modules that don't have a CI system. This project does not seem to have one.

Would you be interested in a pull-request adding GitHub Actions?

**Comment by laurachevalier4** [comment]
Hey @szabgab, thanks for opening this issue! I'm curious if you had something specific in mind? What sort of CI workflows do you think would be beneficial here? I'm not sure if CI would have a worthwhile impact for this library since its upkeep is fairly lite, but I'm open to the idea.
