### ISSUE TITLE
Issue in v25.0.0 - for V18 of the GoogleAds API

### ISSUE THREAD

**Issue by SeanWickfire** [googleads/google-ads-perl#129]
Hello.  It looks like some parameters were removed from package Google::Ads::GoogleAds::V18::Resources::CampaignBudget

Here's a diff between V17 and V18:

bash-4.2$ diff -u V17/Resources/CampaignBudget.pm V18/Resources/CampaignBudget.pm 
--- V17/Resources/CampaignBudget.pm	2024-12-13 18:53:30.000000000 +0000
+++ V18/Resources/CampaignBudget.pm	2024-12-13 18:53:30.000000000 +0000
@@ -12,7 +12,7 @@

-package Google::Ads::GoogleAds::V17::Resources::CampaignBudget;
+package Google::Ads::GoogleAds::V18::Resources::CampaignBudget;
 
 use strict;
 use warnings;
@@ -23,28 +23,9 @@
 sub new {
   my ($class, $args) = @_;
   my $self = {
-alignedBiddingStrategyId      => $args->{alignedBiddingStrategyId},
-amountMicros                  => $args->{amountMicros},
-deliveryMethod                => $args->{deliveryMethod},
-explicitlyShared              => $args->{explicitlyShared},
-hasRecommendedBudget          => $args->{hasRecommendedBudget},
-id                            => $args->{id},
-name                          => $args->{name},
-period                        => $args->{period},
-recommendedBudgetAmountMicros => $args->{recommendedBudgetAmountMicros},
-recommendedBudgetEstimatedChangeWeeklyClicks =>
-$args->{recommendedBudgetEstimatedChangeWeeklyClicks},
-recommendedBudgetEstimatedChangeWeeklyCostMicros =>
-$args->{recommendedBudgetEstimatedChangeWeeklyCostMicros},
-recommendedBudgetEstimatedChangeWeeklyInteractions =>
-$args->{recommendedBudgetEstimatedChangeWeeklyInteractions},
-recommendedBudgetEstimatedChangeWeeklyViews =>
-$args->{recommendedBudgetEstimatedChangeWeeklyViews},
-referenceCount    => $args->{referenceCount},
-resourceName      => $args->{resourceName},
-status            => $args->{status},
-totalAmountMicros => $args->{totalAmountMicros},
-type              => $args->{type}};
+currentAmountMicros        => $args->{currentAmountMicros},
+newStartDate               => $args->{newStartDate},
+recommendedNewAmountMicros => $args->{recommendedNewAmountMicros}};

Thank you for your help!

Sean Brady

**Comment by laurachevalier4** [comment]
Thanks for bringing this to our attention, it was the result in an error during regeneration. Published a patch version with the fix.

**Comment by SeanWickfire** [comment]
@laurachevalier4 - thanks for the quick fix!

- Sean
