### ISSUE TITLE
Minimum Perl Version

### ISSUE THREAD

**Issue by wiredp2p** [googleads/google-ads-perl#93]
Hello, I recently tried to install the latest version of GoogleAds for Perl and it's showing that the minimum perl version is 5.32.1. On Ubuntu, the latest version of perl is 5.30. Furthermore, as per Google Ads API page, the minimum requirement is supposed to be 5.24.1 or greater. This minimum requirement change to 5.32.1 is not possible on Ubuntu. Please advise.

**Comment by laurachevalier4** [comment]
For now, I published a patch as dist version 14.0.1, find it on [CPAN here](https://metacpan.org/release/CHEVALIER/Google-Ads-GoogleAds-Client-14.0.1). 

There's a good chance we'll increase the minimum Perl version in the future, so I recommend upgrading to the minimum supported version of Perl -- regardless of this library, we'd recommend this as best practice. [This article](https://help.dreamhost.com/hc/en-us/articles/360028572351-Installing-a-custom-version-of-Perl-locally) seems like a useful reference for a Perl version upgrade on Ubuntu; you could also cross reference with [StackOverflow](https://stackoverflow.com/questions/1289564/how-should-i-install-more-than-one-version-of-perl).
Alternatively, you could consider using Docker if you don't want to update the Perl version on your system; you can find some documentation on that [here](https://developers.google.com/google-ads/api/docs/client-libs/perl/docker).
